module.exports = {
  "@context": {
    "@version": 1.1,
    "id": "@id",
    "type": "@type",

    "dc": "http://purl.org/dc/terms/",
    "identity": "https://w3id.org/identity#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "http://schema.org/",
    "sec": "https://w3id.org/security#",
    "wl": "https://w3id.org/webledger#",
    "didv": "https://w3id.org/did#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",

    "Config": "wl:Config",
    "Continuity2017": "wl:Continuity2017",
    "Continuity2017Peer": "wl:Continuity2017Peer",
    "ContinuityMergeEvent": "wl:ContinuityMergeEvent",
    "CreateWebLedgerRecord": "wl:CreateWebLedgerRecord",
    "UpdateWebLedgerRecord": "wl:UpdateWebLedgerRecord",
    "DeleteWebLedgerRecord": "wl:DeleteWebLedgerRecord",
    "CryptographicKey": "sec:Key",
    "EquihashProof2017": "sec:EquihashProof2017",
    "EventTypeFilter": "wl:EventTypeFilter",
    "GraphSignature2012": "sec:GraphSignature2012",
    "Identity": "identity:Identity",
    "IssueCredential": "didv:IssueCredential",
    "LinkedDataSignature2015": "sec:LinkedDataSignature2015",
    "LinkedDataSignature2016": "sec:LinkedDataSignature2016",
    "MultiproofValidator2017": "wl:ProofOfSignature2017",
    "ProofOfSignature2017": "wl:ProofOfSignature2017",
    "ProofOfWork2016": "wl:ProofOfWork2016",
    "RsaSigningKey2018": "sec:RsaSigningKey2018",
    "RsaSignature2018": "sec:RsaSignature2018",
    "SequentialList": "wl:SequentialList",
    "SignatureValidator2017": "wl:SignatureValidator2017",
    "UnilateralConsensus2017": "wl:UnilateralConsensus2017",
    "UpdateDidDescription": "didv:UpdateDidDescription",
    "WebLedgerConfiguration": "wl:WebLedgerConfiguration",
    "WebLedgerConfigurationEvent": "wl:WebLedgerConfigurationEvent",
    "WebLedgerEvent": "wl:WebLedgerEvent",
    "WebLedgerEventBlock": "wl:WebLedgerEventBlock",
    "WebLedgerRecord": "wl:WebLedgerRecord",

    "approvedSigner": "wl:approvedSigner",
    "authentication": {"@id": "didv:authenticationSuite", "@type": "@id", "@container": "@set"},
    "blockHeight": "wl:blockHeight",
    "canonicalizationAlgorithm": "sec:canonicalizationAlgorithm",
    "capability": {"@id": "sec:capability", "@type": "@id"},
    "capabilityAction": {"@id": "sec:capabilityAction", "@type": "@vocab"},
    "comment": "rdfs:comment",
    "consensusMethod": {"@id": "wl:consensusMethod", "@type": "@vocab"},
    "created": {"@id": "dc:created", "@type": "xsd:dateTime"},
    "creator": {"@id": "dc:creator", "@type": "@id"},
    "description": "schema:description",
    "digestAlgorithm": "sec:digestAlgorithm",
    "digestValue": "sec:digestValue",
    "domain": "sec:domain",
    "entity": "sec:entity",
    "equihashParameterAlgorithm": "sec:equihashParameterAlgorithm",
    "equihashParameterK": {"@id": "sec:equihashParameterK", "@type": "xsd:integer"},
    "equihashParameterN": {"@id": "sec:equihashParameterN", "@type": "xsd:integer"},
    "event": {"@id": "wl:event", "@container": "@set"},
    "eventFilter": {"@id": "wl:eventFilter", "@type": "@id"},
    "eventHash": "wl:eventHash",
    "eventType": {"@id": "wl:eventType", "@type": "@vocab"},
    "eventValidator": {"@id": "wl:eventValidator", "@type": "@id"},
    "expires": {"@id": "sec:expiration", "@type": "xsd:dateTime"},
    "field": {"@id": "didv:field", "@type": "@id"},
    "grantCapability": {"@id": "didv:grantCapabilitySuite", "@type": "@id", "@container": "@set"},
    "invokeCapability": {"@id": "didv:invokeCapabilitySuite", "@type": "@id", "@container": "@set"},
    "jws": "sec:jws",
    "label": "rdfs:label",
    "ledger": {"@id": "wl:ledger", "@type": "@id"},
    "ledgerConfiguration": {"@id": "wl:ledgerConfiguration", "@type": "@id"},
    "minimumProofsRequired": "sec:minimumProofsRequired",
    "minimumSignaturesRequired": "sec:minimumSignaturesRequired",
    "name": "schema:name",
    "nonce": "sec:nonce",
    "normalizationAlgorithm": "sec:normalizationAlgorithm",
    "operation": {"@id": "wl:operation", "@type": "@id", "@container": ["@graph", "@set"]},
    "owner": {"@id": "sec:owner", "@type": "@id"},
    "parentHash": {"@id": "wl:parentHash", "@container": "@set"},
    "permission": "sec:permission",
    "permittedProofType": "sec:permittedProofType",
    "previousBlock": "wl:previousBlock",
    "previousBlockHash": "wl:previousBlockHash",
    "privateKey": {"@id": "sec:privateKey", "@type": "@id"},
    "privateKeyPem": "sec:privateKeyPem",
    "proof": {"@id": "sec:proof", "@type": "@id", "@container": "@graph"},
    "proofAlgorithm": "sec:proofAlgorithm",
    "proofPurpose": {"@id": "sec:proofPurpose", "@type": "@vocab"},
    "publicKey": {"@id": "sec:publicKey", "@type": "@id", "@container": "@set"},
    "publicKeyPem": "sec:publicKeyPem",
    "record": {"@id": "wl:record", "@type": "@id", "@container": ["@graph", "@set"]},
    "recommendedElector": {"@id": "wl:recommendedElectors", "@container": "@set"},
    "requireEventValidation": "wl:requireEventValidation",
    "requiredProof": "sec:requiredProof",
    "revoked": {"@id": "sec:revoked", "@type": "xsd:dateTime"},
    "seeAlso": {"@id": "rdfs:seeAlso", "@type": "@id"},
    "signature": "sec:signature",
    "signatureAlgorithm": "sec:signatureAlgorithm",
    "signatureValue": "sec:signatureValue",
    "supportedEventType": "wl:supportedEventType",
    "treeHash": "wl:treeHash",
    "voter": {"@id": "wl:voter", "@type": "@id"}
  }
};
